### ISSUE TITLE
repeatedly pop-up error

### ISSUE THREAD

**Issue by AphelG7** [ryuzeen/WutheringWaves-Tools#3]
the window show "non-solaris owners cannot claim supply crates"
![image](https://github.com/ryuzeen/WutheringWaves-Tools/assets/24282872/d88d55a9-fabb-4dcd-9524-b7a0677e1cf1)

**Comment by dani-bytte** [comment]
disable auto pick treasure and auto loot, and don't use them anymore.

**Comment by AphelG7** [comment]
Ok and what is the alternative for this? bc auto loot was why I look for this app

**Comment by dani-bytte** [comment]
this message is something related to auto loot and if it keeps appearing your account may no longer be able to open baus. There is no alternative to auto-loot at the moment
